version: "3.7"
services:
  geth:
    image: "ethereum/client-go:v1.13.15"
    stop_grace_period: 300s
    command:
      - --http
      - --http.api=eth,web3,txpool,net
      - --http.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --http.vhosts=*
      - --http.corsdomain=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/jwtsecret
      - --datadir=/data
      - --state.scheme=path
      - --syncmode=full
      - --networkid=${CHAIN_ID:-32382}
      - --nat=extip:$EXTERNAL_IP
      - --port=$GETH_P2P_PORT
      - --bootnodes=enode://b20e87044eeb41ce50e7d7929e343dc9319d1fd917caca78b77c3355e898c4501d5a33a6c6d97b5184b8f3930f1d58b51ae2fc989174480a28e7f4abf81f791e@84.32.188.95:0?discport=30312
      - --log.file=/logs/geth.log
    ports:
      - $GETH_PORT:8545
      - $GETH_P2P_PORT:$GETH_P2P_PORT
    logging:
       options:
        max-size: "10m"
        max-file: "3"  
    volumes:
      - ./root_signer:/data
      - ./jwtsecret:/jwtsecret
      - ./logs:/logs
  beacon-chain:
    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:v4.2.1"
    command:
      - --datadir=/data
      # No peers to sync with in this testnet, so setting to 0
      - --min-sync-peers=2
      - --minimum-peers-per-subnet=2
      - --genesis-state=/files/genesis.ssz
      - --bootstrap-node=enr:-LG4QNQbzpVjGdqC-Elk9JUABL5P-UGOBGaXDgAeRW6SevulahyjcC8uNyLYBs1FiqRc8JEHoijqUBBtVPoQ8-F5J4iGAZJMwgVNh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhFQgvF-Jc2VjcDI1NmsxoQLyirWTAY--P_8vYX0N0AtINF5p37yEP6N8QI3EoCUBkYN1ZHCCMtQ
      - --chain-config-file=/files/config.yml
      - --chain-id=${CHAIN_ID:-32382}
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --grpc-gateway-corsdomain=*
      - --execution-endpoint=http://geth:8551
      - --accept-terms-of-use
      - --jwt-secret=/jwtsecret
      - --suggested-fee-recipient=$REWARD_RECIPIENT_ADDRESS
      - --verbosity=debug
      - --p2p-host-ip=$EXTERNAL_IP
      - --p2p-tcp-port=$BECONCHAIN_PORT
      - --p2p-udp-port=$BECONCHAIN_PORT
      - --p2p-static-id
      - --enable-debug-rpc-endpoints
      - --log-file=/logs/beacon.log
    ports:
       - $BECONCHAIN_PORT:$BECONCHAIN_PORT/tcp
       - $BECONCHAIN_PORT:$BECONCHAIN_PORT/udp
       - $BECONCHAIN_MONITOR_PORT:8080/tcp
    volumes:
      - ./root_beaconchain:/data
      - ./files:/files
      - ./jwtsecret:/jwtsecret
      - ./logs:/logs
    logging:
       options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      geth:
        condition: service_started
  validator:
    image: "gcr.io/prysmaticlabs/prysm/validator:v4.2.1"
    command:
      - --beacon-rpc-provider=beacon-chain:4000
      - --datadir=/data
      - --accept-terms-of-use
      - --chain-config-file=/files/config.yml
      - --wallet-dir=/files/wallet
      - --wallet-password-file=/files/validator.txt
      - --enable-builder
      - --monitoring-host=0.0.0.0
      - --log-file=/logs/validator.log
    volumes:
      - ./root_validator:/data
      - ./files:/files
      - ./logs:/logs
    ports:
       - $VALIDATOR_MONITOR_PORT:8081/tcp
    logging:
       options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      beacon-chain:
        condition: service_started
  logrotate:
    image: blacklabelops/logrotate
    volumes:
      - "./logs:/var/log/logs"
    environment:
      - LOGS_DIRECTORIES=/var/log/logs
      - LOGROTATE_INTERVAL=daily
      - LOG_FILE_ENDINGS=log
      - LOGROTATE_COPIES=30
      - LOGROTATE_COMPRESSION=compress
    logging:
       options:
        max-size: "10m"
        max-file: "3"          